### ISSUE TITLE
Enable running Features/Scenarios from Gherkin file

### ISSUE THREAD

**Issue by nikolaymatrosov** [nikolaymatrosov/cucumber-go#11]
This run button should work

<img width="487" alt="Screenshot 2024-05-02 at 09 27 41" src="https://github.com/nikolaymatrosov/cucumber-go/assets/1625055/42f1e111-2348-4c85-b549-3a63223ec7b1">

**Comment by nikolaymatrosov** [comment]
Example impl
https://github.com/JetBrains/intellij-plugins/blob/master/cucumber-java/src/org/jetbrains/plugins/cucumber/java/run/CucumberJavaRunConfiguration.java

**Comment by beng90** [comment]
Hi. I was trying to configure this in my IDE, but still no option.
I don't know how to configure godog for .feature files.
I see that there is new template for Go test but that's all.

![image](https://github.com/nikolaymatrosov/cucumber-go/assets/10477361/390a7cee-076a-4c90-803b-fc2bdce4ad55)

**Comment by nikolaymatrosov** [comment]
There is demo repo, where you can find example of feature file and step definitions for it.
https://github.com/nikolaymatrosov/bdd-godog

![godog](https://github.com/nikolaymatrosov/cucumber-go/assets/1625055/d3076f53-092a-4791-bffd-b3de166e605b)
Here is the screenshot showing how to create test run configuration directly from `.feature` file.
