### ISSUE TITLE
Run/debug from Goland with multiple feature files

### ISSUE THREAD

**Issue by lopezdonaque** [nikolaymatrosov/cucumber-go#46]
Hi, 

When you execute the run or debug from Goland, having multiple feature files, it's not able to run the test.
Maybe I'm wrong about how the project should be organized.
I'm trying it with your bdd-godog project.

This could help as a reference to check how it works there:
https://plugins.jetbrains.com/plugin/7512-behat-support

![image](https://github.com/user-attachments/assets/8609b2f6-dd03-49b6-9987-bd7cbbbce87d)

**Comment by nikolaymatrosov** [comment]
Hi,

Thank you for reaching out! The project assumes that each `feature` file has a corresponding test with the same name. To address the issue you're experiencing, please try creating a `TestOther` that points to `other.feature` in its `Paths`. This should help in running the tests correctly.

If you have any further questions or need additional assistance, feel free to ask!
